# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0002_auto_20170410_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='host',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pre_project',
        ),
        migrations.AddField(
            model_name='preproject',
            name='current_project_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='/srv/salt/', verbose_name='版本'),
        ),
    ]
